namespace: prod
replicaCount: 3
activeColor: blue

service:
  type: ClusterIP          # LoadBalancer se ClusterIP kiya

ingress:
  enabled: true
  host: stationhub.in      # PROD root domain

hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  cpuThreshold: 60
  memoryThreshold: 75

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi