namespace: prod
replicaCount: 3
activeColor: blue

service:
  port: 80
  type: ClusterIP

ingress:
  enabled: true
  host: stationhub.in

hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  cpuThreshold: 60
  memoryThreshold: 75

resources:
  requests:
    cpu: 100m        # ← 500m se 100m kiya
    memory: 128Mi    # ← 512Mi se 128Mi kiya
  limits:
    cpu: 250m        # ← 1000m se 250m kiya
    memory: 256Mi    # ← 1Gi se 256Mi kiya

probes:
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 15
    failureThreshold: 3
    timeoutSeconds: 5
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3
    successThreshold: 1
    timeoutSeconds: 5