apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
    color: {{ .Values.activeColor }} # yahan se switch hogi
  ports:
  - port: 80
    targetPort: 80
  type: {{ .Values.service.type }}    # ← yahan se value aayegi