import { Product } from '../types';

export const products: Product[] = [
  {
    id: 1,
    name: 'Premium Notebook A5',
    price: 299,
    category: 'Notebooks',
    image: 'https://images.pexels.com/photos/4226880/pexels-photo-4226880.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'High-quality A5 notebook with 200 pages, perfect for journaling and note-taking.',
    featured: true,
  },
  {
    id: 2,
    name: 'Gel Pen Set (12 Colors)',
    price: 450,
    category: 'Pens',
    image: 'https://images.pexels.com/photos/1000441/pexels-photo-1000441.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Smooth writing gel pens in vibrant colors, ideal for artistic writing.',
    featured: true,
  },
  {
    id: 3,
    name: 'The Complete Guide to Study',
    price: 599,
    category: 'Books',
    image: 'https://images.pexels.com/photos/1194420/pexels-photo-1194420.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Comprehensive study guide with proven techniques for academic success.',
    featured: true,
  },
  {
    id: 4,
    name: 'Ultimate Stationery Kit',
    price: 1299,
    category: 'Stationery Kits',
    image: 'https://images.pexels.com/photos/6942031/pexels-photo-6942031.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Complete stationery kit with pens, pencils, erasers, ruler, and more.',
    featured: true,
  },
  {
    id: 5,
    name: 'Ballpoint Pen Pack (10)',
    price: 150,
    category: 'Pens',
    image: 'https://images.pexels.com/photos/261510/pexels-photo-261510.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Classic blue ballpoint pens for everyday writing needs.',
  },
  {
    id: 6,
    name: 'Spiral Notebook B5',
    price: 249,
    category: 'Notebooks',
    image: 'https://images.pexels.com/photos/796603/pexels-photo-796603.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Durable spiral-bound notebook with perforated pages.',
  },
  {
    id: 7,
    name: 'Business Strategy Book',
    price: 799,
    category: 'Books',
    image: 'https://images.pexels.com/photos/1209843/pexels-photo-1209843.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Learn essential business strategies from industry leaders.',
  },
  {
    id: 8,
    name: 'Fountain Pen Premium',
    price: 899,
    category: 'Pens',
    image: 'https://images.pexels.com/photos/1059108/pexels-photo-1059108.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Elegant fountain pen with smooth ink flow and premium finish.',
  },
  {
    id: 9,
    name: 'Art Supplies Kit',
    price: 1599,
    category: 'Stationery Kits',
    image: 'https://images.pexels.com/photos/1762851/pexels-photo-1762851.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Professional art supplies including markers, colored pencils, and sketch pads.',
  },
  {
    id: 10,
    name: 'Hardcover Planner 2024',
    price: 699,
    category: 'Notebooks',
    image: 'https://images.pexels.com/photos/6373305/pexels-photo-6373305.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Premium hardcover planner with monthly and weekly layouts.',
  },
  {
    id: 11,
    name: 'Creative Writing Guide',
    price: 549,
    category: 'Books',
    image: 'https://images.pexels.com/photos/1370295/pexels-photo-1370295.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Master the art of creative writing with practical exercises.',
  },
  {
    id: 12,
    name: 'Student Essential Kit',
    price: 999,
    category: 'Stationery Kits',
    image: 'https://images.pexels.com/photos/4982923/pexels-photo-4982923.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Everything a student needs: notebooks, pens, geometry box, and more.',
  },
  {
    id: 13,
    name: 'Highlighter Set (6 Colors)',
    price: 199,
    category: 'Pens',
    image: 'https://images.pexels.com/photos/2138126/pexels-photo-2138126.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Bright highlighters for effective study and organization.',
  },
  {
    id: 14,
    name: 'Leather Journal',
    price: 899,
    category: 'Notebooks',
    image: 'https://images.pexels.com/photos/733857/pexels-photo-733857.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Luxurious leather-bound journal with handmade paper.',
  },
  {
    id: 15,
    name: 'Python Programming Book',
    price: 649,
    category: 'Books',
    image: 'https://images.pexels.com/photos/1181671/pexels-photo-1181671.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Learn Python programming from beginner to advanced level.',
  },
  {
    id: 16,
    name: 'Office Desk Organizer Kit',
    price: 1799,
    category: 'Stationery Kits',
    image: 'https://images.pexels.com/photos/7679672/pexels-photo-7679672.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Complete desk organization solution with premium accessories.',
  },
];
