apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.env.DB_PASSWORD | default "" | b64enc | quote }}
  JWT_SECRET:  {{ .Values.env.JWT_SECRET  | default "" | b64enc | quote }}